### ISSUE TITLE
Which Firmware to load in new STM32F407 DISCOVERY board

### ISSUE THREAD

**Issue by mamejay** [DirtyHairy/UnoCart-2600#1]
Hello there.  I am building a unit using a  STM32F407 DISCOVERY board and wanted to know which firmware to install.  You have a firmware.bin and a firmware.hex file.
Sorry if its a silly question but I am new to using this device.
Thanks

**Comment by DirtyHairy** [comment]
I'm sorry, I overlooked your issue. I guess you've got it sorted out by now, but for the record and for future readers: The .bin and the .hex file are the same firmware, which one you'll be using depends on the software you are using for flashing.

Cheers
    -Christian
