### ISSUE TITLE
Crash on 3E+ with > 32K RAM used

### ISSUE THREAD

**Issue by andrew-davie** [DirtyHairy/UnoCart-2600#4]
The attached binary crashes on UnoCart (and PlusCart).

It is 3E+ format, and uses > 32K RAM.
If I change the program so it's < 32K, all works OK.
I believe there is a bug in the 3E+ driver/code.

This ROM works correctly on the latest Stella.

[chess_crash_unocart.zip](https://github.com/DirtyHairy/UnoCart-2600/files/5192969/chess_crash_unocart.zip)

**Comment by DirtyHairy** [comment]
Yeah, I just looked at the code, it currently has a hard limit on 32k RAM. I'll change it.

**Comment by andrew-davie** [comment]
32K RAM *is* the limit for 3E+
But there are 64 BANKS.  Each bank of RAM is 512 bytes.

**Comment by andrew-davie** [comment]
And yes I got that wrong with my title sorry.

**Comment by DirtyHairy** [comment]
Yes, sorry, I made the same error, 32 banks is  the limit I meant 😏

**Comment by DirtyHairy** [comment]
Fixed in v16.
